In [1]:
import numpy as np

In [2]:
a = np.arange(6)


In [3]:
a2 = a[np.newaxis, :]

In [4]:
a2.shape

(1, 6)

In [25]:
arrry02 =  np.empty(10)

In [23]:
print(arrry02)

[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 9.99988867e-321 8.45603440e-307 4.45046007e-307
 2.37667058e-312]


In [27]:
np.linspace(0, 10, num=4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [28]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [30]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
x.ndim

2

In [35]:
x.size

4

In [39]:
x.shape

(2, 2)

In [43]:
a = np.arange(6)

In [44]:
print(a)

[0 1 2 3 4 5]


In [45]:
b = a.reshape(3, 2)

In [46]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [50]:
np.reshape(a, newshape=(1,6 ), order='C')

array([[0, 1, 2, 3, 4, 5]])